before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: waittcp
    main: ./cmd/waittcp/main.go
    ldflags: -s -w
    binary: waittcp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      arm64: arm64
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
